### ISSUE TITLE
Migrate from Glamorous to Emotion

### ISSUE THREAD

**Issue by colebemis** [dasherapp/dasher#40]
Glamorous is most likely going to be deprecated in favor of emotion: https://github.com/paypal/glamorous/issues/419
## Here's why:

- Emotion can do everything glamorous can do
- Emotion can do more than glamorous can do
- Emotion is faster than glamorous
- Emotion is smaller than glamorous
- It's good for the community to consolidate and rally around using and improving a single solution

The glamorous and emotion APIs are very similar so it shouldn't be too hard to switch. Emotion does use a lot of babel plugins so we'll have adjust our babelrc. 

# Do this
* Migrate our codebase from glamorous to emotion

**Comment by lexahall** [comment]
closed by https://github.com/dasherapp/dasher/pull/48
